services:
  backend:
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    container_name: "backend"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:4-management"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
  