version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "backend"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:4-management"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"